app:
  url: ${APP_URL}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /core

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}

spring:
  application:
    name: wireguardbot-core
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000
    url: ${DATASOURCE_URL}   
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql:true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${INSTANCE_ID}

telegram:
  path: ${TELEGRAM_PATH}
  chatid: ${TELEGRAM_CHATID}
  groupid: ${TELEGRAM_GROUPID}
  grouptitle: ${TELEGRAM_GROUPTITLE}
  bot:
    client:
      token: ${TELEGRAM_BOT_CLIENT_TOKEN}
      username: ${TELEGRAM_BOT_CLIENT_USERNAME}
      path: ${app.url}${server.servlet.context-path}${telegram.path}/${telegram.bot.client.token}
    admin:
      token: ${TELEGRAM_BOT_ADMIN_TOKEN}
      username: ${TELEGRAM_BOT_ADMIN_USERNAME}
      path: ${app.url}${server.servlet.context-path}${telegram.path}/${telegram.bot.admin.token}

encryption:
  service:
    key: ${ENCRYPTION_KEY}

scheduler:
  autosendmessage:
    appurl: ${telegram.bot.client.path}
    active: ${SCHEDULER_AUTO_SEND_MESSAGE_ACTIVE}
    chatid: ${telegram.chatid}
    time: ${SCHEDULER_AUTO_SEND_MESSAGE_TIME:50}
    message: ${SCHEDULER_AUTO_SEND_MESSAGE_MESSAGE}

wireguard:
  server:
    name: ${WIREGUARD_SERVER_NAME}
    address: ${WIREGUARD_SERVER_ADDRESS}
    port: ${WIREGUARD_SERVER_PORT}
    publicKey: ${WIREGUARD_SERVER_PUBLIC_KEY}
