app:
  url: ${APP_URL}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /core

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}

spring:
  application:
    name: wireguard-core

eureka:
  client:
    register-with-eureka: false # No se registra a sí mismo
    fetch-registry: false # No consulta a otros servidores
  server:
    enable-self-preservation: true # Evita eliminar servicios muy rápido
    eviction-interval-timer-in-ms: 20000 # tiempo para limpiar instancias inactivas (20s)
  instance:
    hostname: localhost

telegram:
  bot:
    client:
      token: ${TELEGRAM_BOT_CLIENT_TOKEN}
      username: ${TELEGRAM_BOT_CLIENT_USERNAME}
      path: ${app.url}${server.servlet.context-path}telegram/${telegram.bot.client.token}
    admin:
      token: ${TELEGRAM_BOT_ADMIN_TOKEN}
      username: ${TELEGRAM_BOT_ADMIN_USERNAME}
      path: ${app.url}${server.servlet.context-path}/telegram/${telegram.bot.admin.token}