app:
  url: ${APP_URL}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}

spring:
  application:
    name: wireguardbot-core
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000
    url: ${DATASOURCE_URL}   
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: true
        register: true
        service-nace: ${spring.application.name}
        prefer-ip-address: true
        ip-address: ${IP_ADDRESS:127.0.0.1}
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${INSTANCE_ID:${spring.application.name}-${SERVER_PORT}}
telegram:
  path: ${TELEGRAM_PATH}
  bot:
    client:
      token: ${TELEGRAM_BOT_CLIENT_TOKEN}
      username: ${TELEGRAM_BOT_CLIENT_USERNAME}
      path: ${telegram.path}/${telegram.bot.client.token}
    admin:
      token: ${TELEGRAM_BOT_ADMIN_TOKEN}
      username: ${TELEGRAM_BOT_ADMIN_USERNAME}
      path: ${telegram.path}/${telegram.bot.admin.token}

encryption:
  service:
    key: ${ENCRYPTION_KEY}

wireguard:
  server:
    name: ${WIREGUARD_SERVER_NAME}
    address: ${WIREGUARD_SERVER_ADDRESS}
    port: ${WIREGUARD_SERVER_PORT}
    publicKey: ${WIREGUARD_SERVER_PUBLIC_KEY}
