server:
  port: ${SERVER_PORT}

spring:
  application:
    name: wireguardbot-agent
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: ${IP_ADDRESS:127.0.0.1}
        instanceZone: local
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${INSTANCE_ID:${spring.application.name}-${SERVER_PORT}}