server:
  port: ${SERVER_PORT}

spring:
  application:
    name: wireguardbot-agent

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULT_ZONE}
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${INSTANCE_ID}
